// resume-master gab hw/svelte/src/lib/components/NavigationItems.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import type { Route } from '$lib/core';
	import Profiles from '$lib/components/content/Profiles.svelte';
	import Icon from '@iconify/svelte';
	import { base } from "$app/paths";
	export let routes: Route[];
</script>

<ul class="menu menu-lg">
	{#each routes as route, index}
		{@const active = $page.url.pathname === route.path}
		<li>
			<a href="{base}{route.path}" class={active ? 'ring-2 ring-primary' : ''}>
				{#if route.iconClass}
					<div class="mx-1 h-4 w-4 {route.iconClass} {active ? 'bg-primary' : 'bg-neutral'}"></div>
				{/if}
				{#if route.icon}
					<Icon class="text-lg" icon={route.icon} />
				{/if}
				<span class:text-primary={active}>{route.name}</span>
			</a>
			{#if index === routes.length - 1}
				<div class="divider"></div>
			{/if}
		</li>
	{/each}

	<Profiles />
</ul>

// resume-master gab hw/vue/src/components/NavigationItems.vue
<script setup lang="ts">
import ResumeProfiles from './ResumeProfiles.vue';
import { type Route } from '@/router';
defineProps<{ routes: Route[] }>();
</script>

<template>
  <ul class="menu menu-lg">
    <template v-for="(route, index) in routes" :key="route.name">
      <li>
        <RouterLink v-slot="{ isActive }" :to="route.path" active-class="ring-2 ring-primary">
          <div
            v-if="route.iconClass"
            class="w-4 h-4 mx-1"
            :class="[isActive ? 'bg-primary' : 'bg-neutral', route.iconClass]"></div>
          <v-icon v-if="route.icon" :name="route.icon" />
          <span :class="{ 'text-primary': isActive }">{{ route.name }}</span>
        </RouterLink>
        <div v-if="index === routes.length - 1" class="divider"></div>
      </li>
    </template>
    <ResumeProfiles />
  </ul>
</template>
